### ISSUE TITLE
Add paperclip for images

### ISSUE THREAD

**Issue by toriejw** [toriejw/global-pursuit#28]

**Comment by acareaga** [comment]
implement with paperclip on admin dashboard for create pursuits

**Comment by acareaga** [comment]
$ heroku config:set S3_BUCKET_NAME=your_bucket_name
$ heroku config:set AWS_ACCESS_KEY_ID=your_access_key_id
$ heroku config:set AWS_SECRET_ACCESS_KEY=your_secret_access_key
